version: '3'

services:
  server:
    image: expense-tracker-server
    build: ./server
    environment:
      MONGO_URI:
    restart: unless-stopped
    ports:
      - 5000:5000
  client:
    image: expense-tracker-client
    build: ./client
    restart: unless-stopped
    ports:
      - 80:80