version: '3'

services:
  server:
    image: expense-tracker-server
    build: ./server
    environment:
      MONGO_URI:
    restart: unless-stopped
    depends_on:
      - mongodb

  client:
    image: expense-tracker-client
    build: ./client
    restart: unless-stopped
    ports:
      - 8000:80
    depends_on:
      - server

  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    volumes:
      - db-data:/data/db
      
volumes:
  db-data: